---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios'
    msg: "Network device OS not defined or not supported by this role: {{ ansible_network_os }}"

- name: Configure hsrp on interfaces 
  nxos_hsrp:
    interface: "{{ item.name }}"
    group: "{{ item.hsrp.group | default(omit) }}"
    state: "{{ item.hsrp.state | default(omit) }}"  
    vip: "{{ item.hsrp.vip | default( item.ip.address.ipv4_address | ipaddr(1) | ipaddr('address') ) }}"
    version: "{{ item.hsrp.version | default('2') }}"
    preempt: "{{ item.hsrp.preempt | default(omit) }}"
    priority: "{{ item.hsrp.priority | default(omit) }}"
  loop: "{{ interfaces | net_int_filter }}"
  when: >
    ansible_network_os == 'nxos' and
    item.hsrp is defined
  tags: 
    - hsrp_config
    - nxos
# The follwoing 4 tasks are here because the nxos_hsrp module doesn't support some of the features like delay reload,
# preempt delay minimum. Once it does these will be removed and nxos_hsrp used. 
- name: create temp file
  tempfile:
    state: file
    prefix: ansible_
    suffix: "_hsrp_{{ inventory_hostname }}"
  register: network_hsrp_file
  notify: delete temp file
  check_mode: no
  changed_when: false
  tags:
    - hsrp_config

- name: Create hsrp extra config in temp file
  template:
    src: "{{ ansible_network_os }}_hsrp.j2"
    dest: "{{ network_hsrp_file.path }}"
  changed_when: false 
  check_mode: no
  tags: 
    - hsrp_config

- name: display config file content
  debug: msg="{{ lookup('file', network_hsrp_file.path).split('\n') }}"
  when: 
    - hsrp_display_config is defined
    - hsrp_display_config
  ignore_errors: true
  check_mode: no
  tags: 
    - hsrp_config 

- name: Push hsrp config to nxos
  nxos_config:
    src: "{{ network_hsrp_file.path }}"    
  when: >
    ansible_network_os == 'nxos'
  tags: 
    - hsrp_config
    - nxos

- name: delete temp file
  file:
    path: "{{ network_hsrp_file.path }}"
    state: absent
  check_mode: no 
  changed_when: false   
  tags: 
    - hsrp_config 

